### ISSUE TITLE
Is it work for building FBX Python3.7 SDK for Linux?

### ISSUE THREAD

**Issue by gemlongman** [friedererdmann/blender_snippets#1]
is there some similar way of building FBX Python SDK for Linux?

**Comment by friedererdmann** [comment]
Hey! I haven't tried it myself, but yes, it should work (but with cmake afaik instead of visual studio). I'll see if I can give it a try this week.

**Comment by friedererdmann** [comment]
Hey @gemlongman - I tried today to build the fbx sdk with Linux. I used Ubuntu to test with, but seen reports online that it should work with any Linux version.

It definitely works, but is a little bit trickier than Windows, so give it a go and let me know if you run into any issues :)

**Comment by gemlongman** [comment]
Thank you~
I have built my SDK in centos, however, when I import it there is an error which seems to have no clue.
"python3.7/site-packages/fbx.so: undefined symbol: _ZN6fbxsdk7FbxMesh14BuildMergeListERNS_8FbxArrayIiLi16EEEb"

![image](https://user-images.githubusercontent.com/12515180/89369724-8be9e980-d711-11ea-91dc-e8ce848fac1b.png)

_Removed the attached zip, since Autodesk doesn't allow redistributing the compiled FBX SDK_

**Comment by friedererdmann** [comment]
Hey @gemlongman - I made a few adjustments after trying this with CentOS as well. I believe you might be missing the xml2 library.

From the latest test that I made (and just merged into the Markdown), I found that using this combination of installed packages worked:

>The quickest way to install the required development packages is using `sudo yum groupinstall 'Development Tools'`.
>
>Next you will also need `sudo yum install libxml2-devel`

For context: I used latest CentOS (fresh install) and build Python 3.7.8 and did `altinstall` (so `python3.7` for all commands).

**Comment by gemlongman** [comment]
> ay to install the required development packages

before the ImportError happened, there was a make error:
![image](https://user-images.githubusercontent.com/12515180/89484719-a8e5f180-d7d1-11ea-9bf4-ef26bcbc6108.png)
although I used `sudo yum install libxml2-devel`. 

According https://stackoverflow.com/a/21647591 , used `sudo ln -s /root/anaconda3/lib/libxml2.so /usr/lib64/libxml2.so
sudo ln -s /root/anaconda3/lib/libxml2.a /usr/lib64/libxml2.a` fixed the 'xml2' problem, I also tried reinstall it, but the ImportError happened right now still.

**Comment by gemlongman** [comment]
the reason is found~
In fact，“fbx sdk” need to be installed too！
After installing this in the same directory, rebuild it , everything work!
![image](https://user-images.githubusercontent.com/12515180/89500887-00e21f80-d7f5-11ea-923a-dee142d91887.png)

**Comment by friedererdmann** [comment]
Hey! I'm glad it's working now! I changed the wording in the document slightly to make it more clear which downloads are required for Linux, based on your feedback 👍
